import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        canvas: '#000000',
        primary: '#ffffff',
        'on-primary': '#2e3132',
        'accent-blue': '#3b9eff',
        'accent-blue-glow': 'rgba(0,117,255,0.34)',
        'accent-green': '#11ff99',
        'accent-green-glow': 'rgba(34,255,153,0.18)',
        'accent-orange': '#ff801f',
        'accent-orange-glow': 'rgba(255,89,0,0.22)',
        'accent-red': '#ff2047',
        'accent-red-glow': 'rgba(255,32,71,0.34)',
        'accent-yellow': '#ffc53d',
        'surface-card': '#0a0a0c',
        'surface-elevated': '#101012',
        'surface-deep': '#06060a',
        'surface-container': '#201f1f',
        'surface-container-low': '#1c1b1b',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353434',
        'surface-container-lowest': '#0e0e0e',
        'hairline': 'rgba(255,255,255,0.06)',
        'hairline-strong': 'rgba(255,255,255,0.14)',
        'divider-soft': 'rgba(255,255,255,0.04)',
        'charcoal': 'rgba(252,253,255,0.7)',
        'body-text': 'rgba(252,253,255,0.86)',
        'on-surface-variant': '#c4c7c9',
        'on-surface': '#e5e2e1',
        'mute': '#a1a4a5',
        'ash': '#888e90',
        'stone': '#464a4d',
        'outline': '#8e9193',
        'outline-variant': '#444749',
        'error': '#ffb4ab',
        'secondary': '#c8c6c8',
      },
      fontFamily: {
        'display-xxl': ['var(--font-noto-serif)', 'serif'],
        'display-xl': ['var(--font-noto-serif)', 'serif'],
        'display-lg': ['var(--font-hanken)', 'sans-serif'],
        'headline-md': ['var(--font-hanken)', 'sans-serif'],
        'headline-sm': ['var(--font-hanken)', 'sans-serif'],
        'subtitle': ['var(--font-hanken)', 'sans-serif'],
        'body-lg': ['var(--font-hanken)', 'sans-serif'],
        'body-md': ['var(--font-hanken)', 'sans-serif'],
        'body-sm': ['var(--font-inter)', 'sans-serif'],
        'button-md': ['var(--font-inter)', 'sans-serif'],
        'button-sm': ['var(--font-hanken)', 'sans-serif'],
        'caption': ['var(--font-inter)', 'sans-serif'],
        'code-md': ['var(--font-jetbrains)', 'monospace'],
      },
      fontSize: {
        'display-xxl': ['96px', { lineHeight: '1.0', letterSpacing: '-0.96px', fontWeight: '400' }],
        'display-xl': ['72px', { lineHeight: '1.0', letterSpacing: '-0.768px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-2px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.5', letterSpacing: '-0.4px', fontWeight: '500' }],
        'headline-sm': ['20px', { lineHeight: '1.3', letterSpacing: '-0.3px', fontWeight: '500' }],
        'subtitle': ['20px', { lineHeight: '1.3', letterSpacing: '0px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.5', letterSpacing: '0px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', letterSpacing: '-0.4px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.43', letterSpacing: '0px', fontWeight: '400' }],
        'button-md': ['14px', { lineHeight: '1.43', letterSpacing: '0px', fontWeight: '500' }],
        'button-sm': ['14px', { lineHeight: '1.43', letterSpacing: '0.35px', fontWeight: '500' }],
        'caption': ['12px', { lineHeight: '1.5', letterSpacing: '0px', fontWeight: '400' }],
        'code-md': ['13px', { lineHeight: '1.6', letterSpacing: '0px', fontWeight: '400' }],
      },
      spacing: {
        'xxs': '2px',
        'xs': '4px',
        'sm': '8px',
        'md': '12px',
        'lg': '16px',
        'xl': '24px',
        'xxl': '32px',
        'xxxl': '48px',
        'section': '96px',
        'band': '128px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        'sm': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        'full': '9999px',
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'step-pulse': 'step-pulse 2s ease-in-out infinite',
        'bounce-slow': 'bounce 1.5s infinite',
      },
      keyframes: {
        'step-pulse': {
          '0%, 100%': { boxShadow: '0 0 0px rgba(0, 117, 255, 0)', opacity: '0.8' },
          '50%': { boxShadow: '0 0 20px rgba(0, 117, 255, 0.3)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}

export default config
